def sinValue(triRatio):
    match triRatio:
        case "sin0°":
            return "0"
        case "sin30°":
            return "1/2"
        case "sin45°":
            return "√2/2"
        case "sin60°":
            return "√3/2"
        case "sin90°":
            return "1"